// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.massimodz8.collaborativegrouporder.protocol.nano;

@SuppressWarnings("hiding")
public interface InitData {

  public static final class Launch extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Launch[] _emptyArray;
    public static Launch[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Launch[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional uint32 lastLaunched = 1;
    public int lastLaunched;

    public Launch() {
      clear();
    }

    public Launch clear() {
      lastLaunched = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.lastLaunched != 0) {
        output.writeUInt32(1, this.lastLaunched);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.lastLaunched != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(1, this.lastLaunched);
      }
      return size;
    }

    @Override
    public Launch mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.lastLaunched = input.readUInt32();
            break;
          }
        }
      }
    }

    public static Launch parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Launch(), data);
    }

    public static Launch parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Launch().mergeFrom(input);
    }
  }
}
