// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.massimodz8.collaborativegrouporder.protocol.nano;

@SuppressWarnings("hiding")
public interface LevelAdvancement {

  // enum LevelAdvancement
  public static final int LA_UNSPECIFIED = 0;
  public static final int LA_PF_FAST = 1;
  public static final int LA_PF_MEDIUM = 2;
  public static final int LA_PF_SLOW = 3;
}
