// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.massimodz8.collaborativegrouporder.protocol.nano;

@SuppressWarnings("hiding")
public interface RPGClass {

  // enum KnownClass
  public static final int KC_UNSPECIFIED = 0;
  public static final int KC_PF_CORE_BARBARIAN = 1;
  public static final int KC_PF_CORE_BARD = 2;
  public static final int KC_PF_CORE_CLERIC = 3;
  public static final int KC_PF_CORE_DRUID = 4;
  public static final int KC_PF_CORE_FIGHTER = 5;
  public static final int KC_PF_CORE_MONK = 6;
  public static final int KC_PF_CORE_PALADIN = 7;
  public static final int KC_PF_CORE_RANGER = 8;
  public static final int KC_PF_CORE_ROGUE = 9;
  public static final int KC_PF_CORE_SORCERER = 10;
  public static final int KC_PF_CORE_WIZARD = 11;
  public static final int KC_BASE_ALCHEMIST = 12;
  public static final int KC_BASE_CAVALIER = 13;
  public static final int KC_BASE_GUNSLINGER = 14;
  public static final int KC_BASE_INQUISITOR = 15;
  public static final int KC_BASE_MAGUS = 16;
  public static final int KC_BASE_ORACLE = 17;
  public static final int KC_BASE_SUMMONER = 18;
  public static final int KC_BASE_VIGILANTE = 19;
  public static final int KC_BASE_WITCH = 20;
  public static final int KC_ALT_ANTIPALADIN = 21;
  public static final int KC_ALT_NINJA = 22;
  public static final int KC_ALT_SAMURAI = 23;
  public static final int KC_HYB_ARCHANIST = 24;
  public static final int KC_HYB_BLOODRAGER = 25;
  public static final int KC_HYB_BRAWLER = 26;
  public static final int KC_HYB_HUNTER = 27;
  public static final int KC_HYB_INVESTIGATOR = 28;
  public static final int KC_HYB_SHAMAN = 29;
  public static final int KC_HYB_SKALD = 30;
  public static final int KC_HYB_SLAYER = 31;
  public static final int KG_HYB_SWASHBUCLERK = 32;
  public static final int KC_HYB_WARPRIEST = 33;
  public static final int KC_UNC_BARBARIAN = 34;
  public static final int KC_UNC_MONK = 35;
  public static final int KC_UNC_ROGUE = 36;
  public static final int KC_UNC_SUMMONER = 37;
  public static final int KC_OCC_KINETICIST = 38;
  public static final int KC_OCC_MEDIUM = 39;
  public static final int KC_OCC_MESMERIST = 40;
  public static final int KC_OCC_OCCULTIST = 41;
  public static final int KC_OCC_PSYCHIC = 42;
  public static final int KC_OCC_SPIRITUALIST = 43;
  public static final int KC_PRES_ADV_BATTLE_HERALD = 44;
  public static final int KC_PRES_ADV_HOLY_VINDICATOR = 45;
  public static final int KC_PRES_ADV_HORIZON_WALKER = 46;
  public static final int KC_PRES_ADV_CHYMIST = 47;
  public static final int KC_PRES_ADV_SPY = 48;
  public static final int KC_PRES_ADV_WARDEN = 49;
  public static final int KC_PRES_ADV_RAGE_PROPHET = 50;
  public static final int KC_PRES_ADV_STALWART_DEFENDER = 51;
  public static final int KC_PRES_CORE_ARCHER = 52;
  public static final int KC_PRES_CORE_TRICKSTER = 53;
  public static final int KC_PRES_CORE_ASSASSIN = 54;
  public static final int KC_PRES_CORE_DRAGON_DISCIPLE = 55;
  public static final int KC_PRES_CORE_DUELIST = 56;
  public static final int KC_PRES_CORE_ELDRITCH_KNIGHT = 57;
  public static final int KC_PRES_CORE_LOREMASTER = 58;
  public static final int KC_PRES_CORE_MYSTIC_THEURGE = 59;
  public static final int KC_PRES_CORE_PF_CHRONICLER = 60;
  public static final int KC_PRES_CORE_SHADOWDANCER = 61;
  public static final int KC_PRES_OPZ_AGENT_OF_THE_GRAVE = 62;
  public static final int KC_PRES_OPZ_ARCANE_SAVANT = 63;
  public static final int KC_PRES_OPZ_BLOODMAGE = 64;
  public static final int KC_PRES_OPZ_BRIGHTNESS_SEEKER = 65;
  public static final int KC_PRES_OPZ_BROTHER_OF_THE_SEAL = 66;
  public static final int KC_PRES_OPZ_CELESTIAL_KNIGHT = 67;
  public static final int KC_PRES_OPZ_CHAMPION_OF_THE_ENLIGHTENED = 68;
  public static final int KC_PRES_OPZ_CHEVALIER = 69;
  public static final int KC_PRES_OPZ_COASTAL_PRIRATE = 70;
  public static final int KC_PRES_OPZ_COLLEGIATE_ARCANIST = 71;
  public static final int KC_PRES_OPZ_CRIMSON_ASSASSIN = 72;
  public static final int KC_PRES_OPZ_CYPHERMAGE = 73;
  public static final int KC_PRES_OPZ_DAIVRAT = 74;
  public static final int KC_PRES_OPZ_DARK_DELVER = 75;
  public static final int KC_PRES_OPZ_DARKFIRE_ADEPT = 76;
  public static final int KC_PRES_OPZ_DEEP_SEA_PIRATE = 77;
  public static final int KC_PRES_OPZ_DEMONIAC = 78;
  public static final int KC_PRES_OPZ_DIABOLIST = 79;
  public static final int KC_PRES_OPZ_DISSIDENT_OF_DAWN = 80;
  public static final int KC_PRES_OPZ_DIVINE_ASSESSOR = 81;
  public static final int KC_PRES_OPZ_DIVINE_SCION = 82;
  public static final int KC_PRES_OPZ_ENVOY_OF_BALANCE = 83;
  public static final int KC_PRES_OPZ_EVANGELIST = 84;
  public static final int KC_PRES_OPZ_EXALTED = 85;
  public static final int KC_PRES_OPZ_FALSE_PRIEST = 86;
  public static final int KC_PRES_OPZ_FIELD_AGENT = 87;
  public static final int KC_PRES_OPZ_FURIOUS_GUARDIAN = 88;
  public static final int KC_PRES_OPZ_GENIE_BINDER = 89;
  public static final int KC_PRES_OPZ_GOLDEN_LEGIONNAIRE = 90;
  public static final int KC_PRES_OPZ_GRAND_MARSHAL = 91;
  public static final int KC_PRES_OPZ_GRAY_WARDEN = 92;
  public static final int KC_PRES_OPZ_GREEN_FAITH_ACOLYTE = 93;
  public static final int KC_PRES_OPZ_GROUP_LEADER = 94;
  public static final int KC_PRES_OPZ_GUILD_AGENT = 95;
  public static final int KC_PRES_OPZ_GUILD_POISONER = 96;
  public static final int KC_PRES_OPZ_HALFLING_OPPORTUNIST = 97;
  public static final int KC_PRES_OPZ_HARROWER = 98;
  public static final int KC_PRES_OPZ_HELL_KNIGHT_COMMANDER = 99;
  public static final int KC_PRES_OPZ_HELL_KNIGHT_ENFORCER = 100;
  public static final int KC_PRES_OPZ_INHERITORS_CRUSADER = 101;
  public static final int KC_PRES_OPZ_JUSTICIAR = 102;
  public static final int KC_PRES_OPZ_LANTERN_BEARER = 103;
  public static final int KC_PRES_OPZ_LIBERATOR = 104;
  public static final int KC_PRES_OPZ_LION_BLADE = 105;
  public static final int KC_PRES_OPZ_LIVING_MONOLITH = 106;
  public static final int KC_PRES_OPZ_LOW_TEMPLAR = 107;
  public static final int KC_PRES_OPZ_MAGE_OF_THE_THIRD_EYE = 108;
  public static final int KC_PRES_OPZ_MAMMOTH_RIDER = 109;
  public static final int KC_PRES_OPZ_MASTER_OF_STORMS = 110;
  public static final int KC_PRES_OPZ_MYSTERY_CULTIST = 111;
  public static final int KC_PRES_OPZ_NATURAL_ALCHEMIST = 112;
  public static final int KC_PRES_OPZ_NOBLE_SCION = 113;
  public static final int KC_PRES_OPZ_PAIN_TASTER = 114;
  public static final int KC_PRES_OPZ_PIT_FIGHTER = 115;
  public static final int KC_PRES_OPZ_PLANES_WALKER = 116;
  public static final int KC_PRES_OPZ_PURITY_LEGION_ENFORCER = 117;
  public static final int KC_PRES_OPZ_SANCTIFIED_PROPHET = 118;
  public static final int KC_PRES_OPZ_SENTINEL = 119;
  public static final int KC_PRES_OPZ_SLEEPLESS_DETECTIVE = 120;
  public static final int KC_PRES_OPZ_SOUL_WARDEN = 121;
  public static final int KC_PRES_OPZ_SOULEATER = 122;
  public static final int KC_PRES_OPZ_SPHEREWALKER = 123;
  public static final int KC_PRES_OPZ_STEEL_FALCON = 124;
  public static final int KC_PRES_OPZ_STUDENT_OF_WAR = 125;
  public static final int KC_PRES_OPZ_SUN_SEEKER = 126;
  public static final int KC_PRES_OPZ_SWORDLORD = 127;
  public static final int KC_PRES_OPZ_TATTOED_MYSTIC = 128;
  public static final int KC_PRES_OPZ_TECHNOMANCER = 129;
  public static final int KC_PRES_OPZ_UMBRAL_AGENT = 130;
  public static final int KC_PRES_OPZ_VEILED_ILLUSIONIST = 131;
  public static final int KC_PRES_OPZ_WINTER_WITCH = 132;
  public static final int KC_NPC_ADEPT = 133;
  public static final int KC_NPC_ARISTOCRAT = 134;
  public static final int KC_NPC_COMMONER = 135;
  public static final int KC_NPC_EXPERT = 136;
  public static final int KC_NPC_WARRIOR = 137;

  public static final class LevelClass extends
      com.google.protobuf.nano.MessageNano {

    private static volatile LevelClass[] _emptyArray;
    public static LevelClass[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new LevelClass[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string present = 1;
    public java.lang.String present;

    // optional .KnownClass known = 2;
    public int known;

    public LevelClass() {
      clear();
    }

    public LevelClass clear() {
      present = "";
      known = com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_UNSPECIFIED;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.present.equals("")) {
        output.writeString(1, this.present);
      }
      if (this.known != com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_UNSPECIFIED) {
        output.writeInt32(2, this.known);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.present.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.present);
      }
      if (this.known != com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_UNSPECIFIED) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(2, this.known);
      }
      return size;
    }

    @Override
    public LevelClass mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.present = input.readString();
            break;
          }
          case 16: {
            int value = input.readInt32();
            switch (value) {
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_UNSPECIFIED:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PF_CORE_BARBARIAN:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PF_CORE_BARD:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PF_CORE_CLERIC:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PF_CORE_DRUID:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PF_CORE_FIGHTER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PF_CORE_MONK:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PF_CORE_PALADIN:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PF_CORE_RANGER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PF_CORE_ROGUE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PF_CORE_SORCERER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PF_CORE_WIZARD:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_BASE_ALCHEMIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_BASE_CAVALIER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_BASE_GUNSLINGER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_BASE_INQUISITOR:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_BASE_MAGUS:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_BASE_ORACLE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_BASE_SUMMONER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_BASE_VIGILANTE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_BASE_WITCH:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_ALT_ANTIPALADIN:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_ALT_NINJA:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_ALT_SAMURAI:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_HYB_ARCHANIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_HYB_BLOODRAGER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_HYB_BRAWLER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_HYB_HUNTER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_HYB_INVESTIGATOR:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_HYB_SHAMAN:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_HYB_SKALD:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_HYB_SLAYER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KG_HYB_SWASHBUCLERK:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_HYB_WARPRIEST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_UNC_BARBARIAN:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_UNC_MONK:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_UNC_ROGUE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_UNC_SUMMONER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_OCC_KINETICIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_OCC_MEDIUM:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_OCC_MESMERIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_OCC_OCCULTIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_OCC_PSYCHIC:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_OCC_SPIRITUALIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_ADV_BATTLE_HERALD:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_ADV_HOLY_VINDICATOR:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_ADV_HORIZON_WALKER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_ADV_CHYMIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_ADV_SPY:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_ADV_WARDEN:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_ADV_RAGE_PROPHET:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_ADV_STALWART_DEFENDER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_CORE_ARCHER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_CORE_TRICKSTER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_CORE_ASSASSIN:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_CORE_DRAGON_DISCIPLE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_CORE_DUELIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_CORE_ELDRITCH_KNIGHT:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_CORE_LOREMASTER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_CORE_MYSTIC_THEURGE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_CORE_PF_CHRONICLER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_CORE_SHADOWDANCER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_AGENT_OF_THE_GRAVE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_ARCANE_SAVANT:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_BLOODMAGE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_BRIGHTNESS_SEEKER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_BROTHER_OF_THE_SEAL:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_CELESTIAL_KNIGHT:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_CHAMPION_OF_THE_ENLIGHTENED:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_CHEVALIER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_COASTAL_PRIRATE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_COLLEGIATE_ARCANIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_CRIMSON_ASSASSIN:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_CYPHERMAGE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_DAIVRAT:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_DARK_DELVER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_DARKFIRE_ADEPT:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_DEEP_SEA_PIRATE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_DEMONIAC:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_DIABOLIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_DISSIDENT_OF_DAWN:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_DIVINE_ASSESSOR:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_DIVINE_SCION:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_ENVOY_OF_BALANCE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_EVANGELIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_EXALTED:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_FALSE_PRIEST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_FIELD_AGENT:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_FURIOUS_GUARDIAN:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_GENIE_BINDER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_GOLDEN_LEGIONNAIRE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_GRAND_MARSHAL:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_GRAY_WARDEN:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_GREEN_FAITH_ACOLYTE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_GROUP_LEADER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_GUILD_AGENT:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_GUILD_POISONER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_HALFLING_OPPORTUNIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_HARROWER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_HELL_KNIGHT_COMMANDER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_HELL_KNIGHT_ENFORCER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_INHERITORS_CRUSADER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_JUSTICIAR:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_LANTERN_BEARER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_LIBERATOR:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_LION_BLADE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_LIVING_MONOLITH:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_LOW_TEMPLAR:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_MAGE_OF_THE_THIRD_EYE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_MAMMOTH_RIDER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_MASTER_OF_STORMS:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_MYSTERY_CULTIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_NATURAL_ALCHEMIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_NOBLE_SCION:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_PAIN_TASTER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_PIT_FIGHTER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_PLANES_WALKER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_PURITY_LEGION_ENFORCER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_SANCTIFIED_PROPHET:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_SENTINEL:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_SLEEPLESS_DETECTIVE:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_SOUL_WARDEN:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_SOULEATER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_SPHEREWALKER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_STEEL_FALCON:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_STUDENT_OF_WAR:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_SUN_SEEKER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_SWORDLORD:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_TATTOED_MYSTIC:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_TECHNOMANCER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_UMBRAL_AGENT:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_VEILED_ILLUSIONIST:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_PRES_OPZ_WINTER_WITCH:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_NPC_ADEPT:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_NPC_ARISTOCRAT:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_NPC_COMMONER:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_NPC_EXPERT:
              case com.massimodz8.collaborativegrouporder.protocol.nano.RPGClass.KC_NPC_WARRIOR:
                this.known = value;
                break;
            }
            break;
          }
        }
      }
    }

    public static LevelClass parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new LevelClass(), data);
    }

    public static LevelClass parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new LevelClass().mergeFrom(input);
    }
  }
}
